[package]
name = "giveaway"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }
serenity = "0.12.4"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
